language: php

services:
  - mongodb

php:
  - 5.6
  - 7.0
  - 7.3

before_install:
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then echo "memory_limit=3G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "5." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then echo "extension = mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:2} == "7." ]]; then composer config "platform.ext-mongo" "1.6.16" && composer require alcaeus/mongo-php-adapter; fi
  - if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then wget -O ~/.phpenv/versions/$(phpenv version-name)/bin/phpunit https://phar.phpunit.de/phpunit-5.4.6.phar; fi
  - composer self-update

install:
  - composer install
  - cp app/config/parameters.yml.dist app/config/parameters.yml

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  irc:
    channels:
      - "irc.freenode.net#le24eme"
    on_success: change
    on_failure: always
